version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo-blog-data-panp
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro

  fastapi:
    build: .
    container_name: fastapi-blog-data-panp
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
